config/routes.rb
Rails.application.routes.draw do
  root :to => 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
    end
  end
  resources :pictures do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  validates :content, presence: true 
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name, presence: true, length: { in: 1..20 }
  validates :email, length: { in: 1..50 }, 
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :email, uniqueness: true
  validates :email, presence: true, allow_blank: true, on: :update
  validates :email, presence: true, allow_blank: true, on: :edit_case
  validates :password, length: { minimum: 6 }, on: :create
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true, on: :update
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true, on: :edit_case
  has_many :pictures, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  private
  before_action :login_required
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:edit, :show, :update,:destroy]
  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.id = params[:id]
    @picture.user_id = current_user.id
    if @picture.id?
      render :edit and return if @picture.invalid?
    else
      render :new if @picture.invalid?
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to pictures_path, notice: "投稿しました"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if params[:back]
      render :edit
    else
      if @picture.update(picture_params)
        redirect_to picture_path(@picture.id), notice: "編集しました"
      else
        render :edit
      end
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "投稿を削除しました！"
  end
  

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:content, :id, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :confirm]
  before_action :set_user, only: [:edit, :show, :update,:destroy]
  def new
    @user = User.new
  end
  
  def confirm
    @user = params[:id] ? User.find(params[:id]) : User.new(user_params)
    if @user.id?
      @user.assign_attributes(user_params)
      render :edit and return if @user.invalid?(:edit_case)
    else
      @user.id =  params[:id] ? params[:id] : nil
      render :new if @user.invalid?
    end
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render :new
    else
      if @user.save
        redirect_to user_path(@user.id), notice: "ユーザー登録完了しました！"
      else
        render :new
      end
    end
  end
  
  def show
  end

  def edit
  end

  def update
    if params[:back]
      render :edit
    else
      if @user.update(user_params)
        redirect_to user_path(@user.id), notice: "ユーザー編集完了しました！"
      else
        render :edit
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to new_user_path, notice: "ご利用ありがとうございました！登録情報を削除しました！"
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def confirm_action_picture
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit' || action_name == 'update'
      confirm_picture_path
    end
  end
  def confirm_id_picture
    unless @picture.id?
      pictures_path
    else
      picture_path
    end
  end
  def confirm_request_picture
    @picture.id ? 'patch' : 'po sst'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def confirm_action
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_users_path
    elsif action_name == 'edit' || action_name == 'update'
      confirm_user_path
    end
  end
  def confirm_id
    unless @user.id?
      users_path
    else
      user_path
    end
  end
  def confirm_request
    @user.id ? 'patch' : 'post'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Footprints</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="body_wrapper">
      <header>
        <div class="header_nav">       
          <div class="logo">
            <p>footprints</p>
          </div>
          <% if logged_in? %>  
            <ul class="nav_list">
              <li class=nav_items><%= link_to "プロフィール", user_path(current_user.id) %></li>
              <li class=nav_items><%= link_to "投稿一覧", pictures_path %></li>
              <li class=nav_items><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
            </ul>
          <% else %>
            <ul class="nav_list">
              <li class=nav_items><%= link_to "サインアップ", new_user_path %></li>
              <li class=nav_items><%= link_to "ログイン", new_session_path %></li>
            </ul>
          <% end %>
        </div>
      </header>
      <div class="flash_message">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key} bg-success") %>
        <% end %>
      </div>
      <%= yield %>
      <footer>
        <div>
          <p>© 2021 tetsuya</p>
        </div>
      </footer>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    </body>
  </div>
</html>

app/views/pictures/_form.html.erb
<% if @picture.errors.any? %>
  <div id="error_explanation">
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @picture.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @picture, local: true ,url: confirm_action_picture) do |f| %>
  <div class="table_wrapper">
    <%= f.hidden_field :user %>
    <p class="comment_label"><%= f.label :'コメント' %></p>
    <%= f.text_area :content %>
    <div>
      <%= f.file_field :image %>
      <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="button">
      <%= f.submit "入力内容確認", class: "btn btn-primary button_margin" %>
      <%= link_to "一覧に戻る", pictures_path, class: "btn btn-primary button_margin" %>
    </div>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<div class="main_wrapper">
  <h3>内容確認ページ</h3>
  <%= form_with(model: @picture, local: true ,url: confirm_id_picture, method: confirm_request_picture) do |f| %>
    <div class="table_wrapper">
      <div>
        <% if @picture.id %>
          <p>投稿番号 : <%= @picture.id %></p> 
        <% end %>
        <p>名前 : <%= @picture.user.name %></p> 
        <%= f.hidden_field :content %>
        <p>コメント : <%= @picture.content %></p>
        <p>Image:</p>
        <%= f.hidden_field :image_cache %>
        <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
      </div> 
      <div class="button">
        <% if @picture.id %>
          <%= f.submit "変更", class: "btn btn-primary button_margin" %>
        <% else %>
          <%= f.submit "投稿", class: "btn btn-primary button_margin"  %>
        <% end %>
        <%= f.submit "戻る", name: 'back', class: "btn btn-primary button_margin" %>
      </div>
    </div>
  <% end %>
  <div class="index_button">
    <%= button_to "一覧画面へ戻る", {controller: 'pictures', action: 'index'}, {method: :get, class: "btn btn-primary button_margin" } %>
  </div>
</div>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/edit.html.erb
<div class="main_wrapper">
  <h3>編集ページ</h3>
  <%= render 'form' %>
</div>

app/views/pictures/index.html.erb
<div class="main_wrapper fixex_button_parents">
  <h3 class="page_title">みんなの投稿</h3>
  <div class="table_wrapper pictures_wrapper">
    <% @pictures.each do |p| %>
      <div class="picture_list">
        <tr class="picture_content">
          <td><p class="picture_content_item"> 名前 : <%= p.user.name %></p></td>
          <td><p class="picture_content_item"> コメント : <%= p.content %></p></td>
          <% if p.image.url %>
            <td class="picture_content_item"><p class="picture_tag">picture</p></td>
            <td>
              <%= link_to p.image.url, 'data-lightbox': p.image do %>
                <%= image_tag p.image.url, class: "picture" if p.image? %>
              <% end %>
            </td>
          <% end %>  
          <div>
            <% if p.user == current_user %>
              <%= link_to "詳細", picture_path(p.id), class: "btn btn-primary button_item" %>
              <%= link_to "編集", edit_picture_path(p.id), class: "btn btn-primary button_item" %>
              <%= link_to "削除", picture_path(p.id), method: :delete, data: { confirm: '本当に削除しますか？'}, class: "btn btn-primary button_item" %>
            <% end %>
          </div>
        </tr>
      </div>
    <% end %>
  </div>
</div>


<br>
<%= link_to "投稿する", new_picture_path, class: "fixed_button" %>

app/views/pictures/new.html.erb
<div class="main_wrapper">
  <h3>投稿ページ</h3>
  <%= render 'form' %>
</div>

app/views/pictures/show.html.erb
<div class="main_wrapper">
  <h3>投稿詳細ページ</h3>
  <div class="table_wrapper">
    <div>
      <p>名前 : <%= @picture.user.name %></p> 
      <p>投稿番号 : <%= @picture.id %></p> 
      <p>コメント : <%= @picture.content %></p>
      <% if @picture.image? %>
        <p>Image: </p>
        <%= image_tag @picture.image.url %>
      <% end %>
    </div>
    <div class="button">
      <%= link_to "編集", edit_picture_path, class: "btn btn-primary button_margin" %>
      <%= link_to "削除", picture_path(@picture.id), method: :delete, data: { confirm: '本当に削除しますか？'}, class: "btn btn-primary button_margin" %>
      <%= link_to "一覧に戻る", pictures_path, class: "btn btn-primary button_margin" %>
    </div>
  </div>
</div>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true, url:confirm_action) do |f| %>  
  <div class="table_wrapper">
    <table>
      <tbody>
        <tr>
          <td><%= f.label :"名前" %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :"メールアドレス" %></td>
          <td><%= f.email_field :email %></td>
        </tr>
        <tr>
          <td><%= f.label :"パスワード"%></td>
          <td><%= f.password_field :password %></td>
        </tr>
        <tr>
          <td><%= f.label :"パスワード確認用" %></td>
          <td><%= f.password_field :password_confirmation %></td>
        </tr>
      </tbody>
    </table>
    <div class="button">
      <%= f.submit "入力内容確認", class: "btn btn-primary #{'button_margin' if @user.id?}" %>
      <% if @user.id? %>
          <%= link_to '戻る', user_path(@user.id), class: "btn btn-primary button_margin" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/confirm.html.erb
<div class="main_wrapper">
  <h3>入力内容確認</h3>
  <%= form_with(model: @user, local: true, url: confirm_id, method: confirm_request) do |f| %>
    <div class="table_wrapper">
      <table>
        <tbody>
          <tr>
            <td><p>名前:</p></td>
            <td><%= @user.name %></td>
          </tr>
            <td><p>メールアドレス:</p></td>
            <td><%= @user.email %></td>
          <tr>
          </tr>
            <td><p>パスワード : </p></td>
            <td>＊＊＊＊＊＊＊＊</td>
          <tr>
          </tr>
            <td><p>パスワード確認用 : </p></td>
            <td>＊＊＊＊＊＊＊＊</td>
          <tr>
          <tr>
            <td class="button"><%= f.submit "登録する", class: "btn btn-primary" %></td>      
            <td class="button"><%= f.submit "戻る", name: 'back', class: "btn btn-primary" %></td>
          </tr>
        </tbody>
      </table>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :password %>
      <%= f.hidden_field :password_confirmation %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="main_wrapper">
  <h3>ユーザー情報変更</h3>
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class="main_wrapper">
  <h3>サインアップ</h3>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="main_wrapper">
  <h3>プロフィール</h3>
  <div class="table_wrapper">
    <table>
      <tbody>
        <tr>
          <td><p>名前:</p></td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td><p>メールアドレス:</p></td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td><p>パスワード : </p></td>
          <td>＊＊＊＊＊＊＊＊</td>
        </tr>
        <tr>
          <td><p>パスワード確認用 : </p></td>
          <td>＊＊＊＊＊＊＊＊</td>
        </tr>
        <tr>
          <td class="button"><%= link_to "投稿", new_picture_path, class: "btn btn-primary" %></td>
          <td class="button"><%= link_to "編集", edit_user_path(@user.id), class: "btn btn-primary" %></td>
          <td class="button"><%= link_to '退会', user_path(@user.id), method: :delete, data: { confirm: '本当に退会しますか？'}, class: "btn btn-primary" %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div> 